### ISSUE TITLE
Extend format: algorithm paramters

### ISSUE THREAD

**Issue by mlindauer** [coseal/aslib_data#11]
Hi, 

related to #10, I would like to discuss with you how we can extend the format such that we can provide more information regarding algorithms, e.g., (hyper-)parameter configurations.

Since the information should be machine readable, it should live in the `description.txt` (in yaml format).
I would propose that we have an additional keyword `metainfo_algorithms` and the scenario creators can decide what they want to specify in there -- so all information are optional.
In return, I would prefer that algorithm names are limited to 15 characters.

Here an example, for the ASP-POTASSCO scenario:

```
metainfo_algorithms:
  clasp-h1:
    configuration: --heuristic berkmin  --sat-prepro no
    version: 2.1.3
  clasp-h2:
    configuration: --sat-prepro yes
    version: 2.1.3
```

I could also imagine that "call strings" or "textual descriptions" could be provided for each algorithm.

What do you think?

Cheers,
Marius
